Repository quad-squad/bowling-app, pull requests merged in 2018-03, with the labels that each got.

#3 Add toolbar to landing page
  app/static/package.json
  app/static/src/app/app.component.html
  app/static/src/app/app.module.ts
  app/static/src/index.html
  app/static/src/styles.css
Labels: enhancement, front-end

#5 Add routing to toolbar
  app/static/src/app/app.module.ts
  app/static/src/index.html
  app/static/src/styles.css
Labels: enhancement, front-end

#7 Correct dependencies
  app/static/package.json
Labels: hot-fix

#11 Add home component & improve routing
  app/static/src/app/app.component.html
  app/static/src/app/app.module.ts
  app/static/src/index.html
Labels: enhancement, front-end

#12 Insert users into database
  app/default/routes.py
  app/services/Database.py
  app/services/__init__.py
  app/services/get_frame.py
  manage.py
Labels: back-end, enhancement

#16 Query users with certain group name
  app/default/routes.py
  app/services/Database.py
Labels: back-end, enhancement
